development:
  adapter: postgresql
  encoding: unicode
  database: Aerosanidad_development
  pool: 5
  username: postgres 
  password: postgres
  host: localhost
  port: 5433



test:
  adapter: postgresql
  encoding: unicode
  database: Aerosanidad_test
  pool: 5
  username: postgres 
  password: postgres
  host: localhost
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: Aerosanidad_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433