Cie102.create!([
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A000", descripcion: "COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO CHOLERAE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A001", descripcion: "COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO EL TOR"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A009", descripcion: "COLERA NO ESPECIFICADO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A010", descripcion: "FIEBRE TIFOIDEA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A011", descripcion: "FIEBRE PARATIFOIDEA A"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A012", descripcion: "FIEBRE PARATIFOIDEA B"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A013", descripcion: "FIEBRE PARATIFOIDEA C"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A014", descripcion: "FIEBRE PARATIFOIDEA, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A020", descripcion: "ENTERITIS DEBIDA A SALMONELLA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A021", descripcion: "SEPTICEMIA DEBIDA A SALMONELLA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A022", descripcion: "INFECCIONES LOCALIZADAS DEBIDA A SALMONELLA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A028", descripcion: "OTRAS INFECCIONES ESPECIFICADAS COMO DEBIDAS A SALMONELLA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A029", descripcion: "INFECCIÓN DEBIDA A SALMONELLA NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A030", descripcion: "SHIGELOSIS DEBIDA A SHIGELLA DYSENTERIAE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A031", descripcion: "SHIGELOSIS DEBIDA A SHIGELLA FLEXNERI"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A032", descripcion: "SHIGELOSIS DEBIDA A SHIGELLA BOYDII"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A033", descripcion: "SHIGELOSIS DEBIDA A SHIGELLA SONNEI"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A038", descripcion: "OTRAS SHIGELOSIS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A039", descripcion: "SHIGELOSIS DE TIPO NO ESPECIFICADO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A040", descripcion: "INFECCION DEBIDA A ESCHERICHIA COLI ENTEROPATOGENA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A041", descripcion: "INFECCION DEBIDA A ESCHERICHIA COLI ENTEROTOXIGENA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A042", descripcion: "INFECCION DEBIDA A ESCHERICHIA COLI ENTEROINVASIVA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A043", descripcion: "INFECCION DEBIDA A ESCHERICHIA COLI ENTEROHEMORRAGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A044", descripcion: "OTRAS INFECCIONES INTESTINALES DEBIDAS A ESCHERICHIA COLI"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A045", descripcion: "ENTERITIS DEBIDA A CAMPYLOBACTER"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A046", descripcion: "ENTERITIS DEBIDA A YERSINIA ENTEROCOLITICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A047", descripcion: "ENTEROCOLITIS DEBIDA A CLOSTRIDIUM DIFFICILE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A048", descripcion: "OTRAS INFECCIONES INTESTINALES BACTERIANAS ESPECIFICADAS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A049", descripcion: "INFECCION INTESTINAL BACTERIANA, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A050", descripcion: "INTOXICACION ALIMENTARIA ESTAFILOCOCICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A051", descripcion: "BOTULISMO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A052", descripcion: "INTOXICACION ALIMENTARIA DEBIDA A CLOSTRIDIUM PERFRINGENS [CLOSTRIDIUM WELCHII]"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A053", descripcion: "INTOXICACION ALIMENTARIA DEBIDA A VIBRIO PARAHAEMOLYTICUS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A054", descripcion: "INTOXICACION ALIMENTARIA DEBIDA A BACILLUS CEREUS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A058", descripcion: "OTRAS INTOXICACIONES ALIMENTARIAS DEBIDAS A BACTERIAS ESPECIFICADAS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A059", descripcion: "INTOXICACION ALIMENTARIA BACTERIANA, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A060", descripcion: "DISENTERIA AMEBIANA AGUDA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A061", descripcion: "AMEBIASIS INTESTINAL CRONICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A062", descripcion: "COLITIS AMEBIANA NO DISENTERICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A063", descripcion: "AMEBOMA INTESTINAL"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A064", descripcion: "ABSCESO AMEBIANO DEL HIGADO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A065", descripcion: "ABSCESO AMEBIANO DEL PULMON (J99.8*)"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A066", descripcion: "ABSCESO AMEBIANO DEL CEREBRO (G07*)"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A067", descripcion: "AMEBIASIS CUTANEA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A068", descripcion: "INFECCION AMEBIANA DE OTRAS LOCALIZACIONES"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A069", descripcion: "AMEBIASIS, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A070", descripcion: "BALANTIDIASIS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A071", descripcion: "GIARDIASIS [LAMBLIASIS]"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A072", descripcion: "CRIPTOSPORIDIOSIS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A073", descripcion: "ISOSPORIASIS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A078", descripcion: "OTRAS ENFERMEDADES INTESTINALES ESPECIFICADAS DEBIDAS A PROTOZOARIOS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A079", descripcion: "ENFERMEDAD INTESTINAL DEBIDA A PROTOZOARIOS, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A080", descripcion: "ENTERITIS DEBIDA A ROTAVIRUS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A081", descripcion: "GASTROENTEROPATIA AGUDA DEBIDA AL AGENTE DE NORWALK"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A082", descripcion: "ENTERITIS DEBIDA A ADENOVIRUS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A083", descripcion: "OTRAS ENTERITIS VIRALES"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A084", descripcion: "INFECCION INTESTINAL VIRAL, SIN OTRA ESPECIFICACION"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A085", descripcion: "OTRAS INFECCIONES INTESTINALES ESPECIFICADAS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A09X", descripcion: "DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN INFECCIOSO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A228", descripcion: "OTRAS FORMAS DE CARBUNCO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A150", descripcion: "TUBERCULOSIS DEL PULMON, CONFIRMADA POR HALLAZGO MICROSCOPICO DEL BACILO TUBERCULOSO EN ESPUTO, CON O SIN CULTIVO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A151", descripcion: "TUBERCULOSIS DEL PULMON, CONFIRMADA UNICAMENTE POR CULTIVO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A152", descripcion: "TUBERCULOSIS DEL PULMON, CONFIRMADA HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A153", descripcion: "TUBERCULOSIS DEL PULMON , CONFIRMADA POR MEDIOS NO ESPECIFICADOS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A154", descripcion: "TUBERCULOSIS DE GANGLIOS LINFATICOS INTRATORACICOS, CONFIRMADA BACTERIOLOGICA E HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A155", descripcion: "TUBERCULOSIS DE LARINGE, TRAQUEA Y BRONQUIOS, CONFIRMADA BACTERIOLOGICA E HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A156", descripcion: "PLEURESIA TUBERCULOSA, CONFIRMADA BACTERIOLOGICA E HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A157", descripcion: "TUBERCULOSIS RESPIRATORIA PRIMARIA, CONFIRMADA BACTERIOLOGICA E HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A158", descripcion: "OTRAS TUBERCULOSIS RESPIRATORIAS, CONFIRMADAS BACTERIOLOGICA E HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A159", descripcion: "TUBERCULOSIS RESPIRATORIA NO ESPECIFICADA, CONFIRMADA BACTERIOLOGICAMENTE E HISTOLOGICAMENTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A160", descripcion: "TUBERCULOSIS DEL PULMON, CON EXAMEN BACTERIOLOGICO E HISTOLOGICO NEGATIVOS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A161", descripcion: "TUBERCULOSIS DEL PULMON, SIN EXAMEN BACTERIOLOGICO E HISTOLOGICO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A162", descripcion: "TUBERCULOSIS DE PULMON, SIN MENCION DE CONFIRMACION BACTERIOLOGICA O HISTOLOGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A163", descripcion: "TUBERCULOSIS DE GANGLIOS LINFATICOS INTRATORACICOS, SIN MENCION DE CONFIRMACION BACTERIOLOGICA O HISTOLOGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A164", descripcion: "TUBERCULOSIS DE LARINGE, TRAQUEA Y BRONQUIOS, SIN MENCION DE CONFIRMACION BACTERIOLOGICA O HISTOLOGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A165", descripcion: "PLEURESIA TUBERCULOSA, SIN MENCION DE CONFIRMACION BACTERIOLOGICA E HISTOLOGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A167", descripcion: "TUBERCULOSIS RESPIRATORIA PRIMARIA, SIN MENCION DE CONFIRMACION BACTERIOLOGICA E HISTOLOGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A168", descripcion: "OTRAS TUBERCULOSIS RESPIRATORIAS, SIN MENCION DE CONFIRMACION"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A169", descripcion: "TUBERCULOSIS RESPIRATORIA NO ESPECIFICADA, SIN MENCION DE CONFIRMACION BACTERIOLOGICA O HISTOLOGICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A170", descripcion: "MENINGITIS TUBERCULOSA (G01*)"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A171", descripcion: "TUBERCULOMA MENINGEO (G07*)"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A178", descripcion: "OTRAS TUBERCULOSIS DEL SISTEMA NERVIOSO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A179", descripcion: "TUBERCULOSIS DEL SISTEMA NERVIOSO, NO ESPECIFICADA (G99.8*)"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A180", descripcion: "TUBERCULOSIS DE HUESOS Y ARTICULACIONES"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A181", descripcion: "TUBERCULOSIS DEL APARATO GENITOURINARIO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A182", descripcion: "LINFADENOPATIA PERIFERICA TUBERCULOSA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A183", descripcion: "TUBERCULOSIS DE LOS INTESTINOS, EL PERITONEO Y LOS GANGLIOS MESENTERICOS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A184", descripcion: "TUBERCULOSIS DE LA PIEL Y EL TEJIDO SUBCUTANEO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A185", descripcion: "TUBERCULOSIS DEL OJO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A186", descripcion: "TUBERCULOSIS DEL OIDO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A187", descripcion: "TUBERCULOSIS DE GLANDULAS SUPRARRENALES (E35.1*)"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A188", descripcion: "TUBERCULOSIS DE OTROS ORGANOS ESPECIFICADOS"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A190", descripcion: "TUBERCULOSIS MILIAR AGUDA DE UN SOLO SITIO ESPECIFICADO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A191", descripcion: "TUBERCULOSIS MILIAR AGUDA DE SITIOS MULTIPLES"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A192", descripcion: "TUBERCULOSIS MILIAR AGUDA, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A198", descripcion: "OTRAS TUBERCULOSIS MILIARES"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A199", descripcion: "TUBERCULOSIS MILIAR, SIN OTRA ESPECIFICACION"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A200", descripcion: "PESTE BUBONICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A201", descripcion: "PESTE CELULOCUTANEA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A202", descripcion: "PESTE NEUMONICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A203", descripcion: "MENINGITIS POR PESTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A207", descripcion: "PESTE SEPTICEMICA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A208", descripcion: "OTRAS FORMAS DE PESTE"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A209", descripcion: "PESTE, NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A210", descripcion: "TULAREMIA ULCEROGLANDULAR"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A211", descripcion: "TULAREMIA OCULOGLANDULAR"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A212", descripcion: "TULAREMIA PULMONAR"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A213", descripcion: "TULAREMIA GASTROINTESTINAL"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A217", descripcion: "TULAREMIA GENERALIZADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A218", descripcion: "OTRAS FORMAS DE TULAREMIA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A219", descripcion: "TULAREMIA , NO ESPECIFICADA"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A220", descripcion: "CARBUNCO CUTANEO"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A221", descripcion: "CARBUNCO PULMONAR"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A222", descripcion: "CARBUNCO GASTROINTESTINAL"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A227", descripcion: "CARBUNCO SEPTICEMICO"},
  {familia: "Neoplasias", codigo: "C12X", descripcion: "TUMOR MALIGNO DEL SENO PIRIFORME"},
  {familia: "Enfermedades infecciosas y parasitarias.", codigo: "A229", descripcion: "CARBUNCO, NO ESPECIFICADO"},

